plugins { id("com.android.application");id("org.jetbrains.kotlin.android");id("org.jetbrains.kotlin.plugin.compose");id("com.google.devtools.ksp") }
android {
 namespace="ca.monwallet.app";compileSdk=35
    defaultConfig { applicationId="ca.monwallet.app";minSdk=26;targetSdk=35;versionCode=providers.gradleProperty("versionCode").orNull?.toInt()?:2024;versionName=providers.gradleProperty("versionName").orNull?:"0.2.23";testInstrumentationRunner="androidx.test.runner.AndroidJUnitRunner"
  fun config(n:String, fallback:String="")="\""+(System.getenv(n)?.takeIf { it.isNotBlank() }?:fallback).replace("\\","\\\\").replace("\"","\\\"")+"\""
  // These are public client configuration values; RLS protects all user records.
  buildConfigField("String","SUPABASE_URL",config("SUPABASE_URL","https://prwlnxbqttxfjxpehmok.supabase.co"));buildConfigField("String","SUPABASE_ANON_KEY",config("SUPABASE_ANON_KEY","sb_publishable_mFW_ScYpHPAeScXk0SZxbg_QEGoCx8J"));buildConfigField("String","GOOGLE_WEB_CLIENT_ID",config("GOOGLE_WEB_CLIENT_ID","158439565502-oa8ksq1phh6mcrq60ftbqhm0diotcdv0.apps.googleusercontent.com"));buildConfigField("String","UPDATE_MANIFEST_URL",config("UPDATE_MANIFEST_URL"));buildConfigField("String","CANADA_FINANCIALS_URL",config("CANADA_FINANCIALS_URL"));buildConfigField("String","FINVIZ_FINANCIALS_URL",config("FINVIZ_FINANCIALS_URL"));manifestPlaceholders["appLabel"]="Mon Wallet";buildConfigField("String","AUTH_CALLBACK_PATH","\"/callback\"");manifestPlaceholders["authCallbackPath"]="/callback"
 }
 buildFeatures{compose=true;buildConfig=true}
 compileOptions { sourceCompatibility=JavaVersion.VERSION_17;targetCompatibility=JavaVersion.VERSION_17 };kotlinOptions{jvmTarget="17"}
 signingConfigs{if(!System.getenv("MONWALLET_STORE_FILE").isNullOrBlank())create("release"){storeFile=file(System.getenv("MONWALLET_STORE_FILE"));storePassword=System.getenv("MONWALLET_STORE_PASSWORD");keyAlias=System.getenv("MONWALLET_KEY_ALIAS");keyPassword=System.getenv("MONWALLET_KEY_PASSWORD")}}
 buildTypes{debug{applicationIdSuffix=".preview2";versionNameSuffix="-preview";manifestPlaceholders["appLabel"]="Mon Wallet • Aperçu";buildConfigField("String","AUTH_CALLBACK_PATH","\"/callback-preview\"");manifestPlaceholders["authCallbackPath"]="/callback-preview"};release{isMinifyEnabled=false;signingConfig=signingConfigs.findByName("release")}}
 packaging{resources.excludes+="/META-INF/{AL2.0,LGPL2.1}"}
 testOptions{unitTests.isIncludeAndroidResources=true;unitTests.all{it.systemProperty("robolectric.dependency.repo.url","https://repo.maven.apache.org/maven2");System.getenv("MONWALLET_TEST_SDK_DIR")?.let{path->it.systemProperty("robolectric.offline","true");it.systemProperty("robolectric.dependency.dir",path)}}}
}
ksp{arg("room.schemaLocation","$projectDir/schemas")}
dependencies{
 implementation(platform("androidx.compose:compose-bom:2025.04.01"));implementation("androidx.core:core-ktx:1.16.0");implementation("androidx.activity:activity-compose:1.10.1");implementation("androidx.fragment:fragment-ktx:1.8.6");implementation("androidx.compose.material3:material3");implementation("androidx.compose.material:material-icons-extended");implementation("androidx.compose.ui:ui");implementation("androidx.lifecycle:lifecycle-viewmodel-compose:2.9.0");implementation("androidx.lifecycle:lifecycle-runtime-compose:2.9.0");implementation("androidx.navigation:navigation-compose:2.8.9");implementation("androidx.room:room-runtime:2.7.1");implementation("androidx.room:room-ktx:2.7.1");ksp("androidx.room:room-compiler:2.7.1");implementation("androidx.datastore:datastore-preferences:1.1.4");implementation("androidx.work:work-runtime-ktx:2.10.1");implementation("androidx.biometric:biometric:1.1.0");implementation("androidx.browser:browser:1.8.0");implementation("androidx.credentials:credentials:1.5.0");implementation("androidx.credentials:credentials-play-services-auth:1.5.0");implementation("com.google.android.libraries.identity.googleid:googleid:1.1.1");implementation("com.squareup.okhttp3:okhttp:4.12.0");implementation("com.google.code.gson:gson:2.12.1");testImplementation("junit:junit:4.13.2");testImplementation("org.robolectric:robolectric:4.14.1");testImplementation("androidx.test:core:1.6.1");testImplementation("androidx.room:room-testing:2.7.1");androidTestImplementation("androidx.test:runner:1.6.2");androidTestImplementation("androidx.test.ext:junit:1.2.1");androidTestImplementation("androidx.test.uiautomator:uiautomator:2.3.0")
}
